apiVersion: v1
kind: Service
metadata:
  name: lending-service
  labels:
    app: lending-service
spec:
  type: ClusterIP
  ports:
    - port: 8484
      targetPort: 8484
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: grpc
  selector:
    app: lending-service
