apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        {{- if .Values.prometheus.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "{{ .Values.prometheus.path }}"
        prometheus.io/port: "{{ .Values.service.httpPort }}"
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.httpPort }}
              name: http
            - containerPort: {{ .Values.service.grpcPort }}
              name: grpc
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "postgres"
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.database.url }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.database.username }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.database.password }}"
            - name: KAFKA_SERVERS
              value: "{{ .Values.kafka.servers }}"
            - name: KAFKA_ENABLED
              value: "{{ .Values.kafka.enabled }}"
            - name: REDIS_HOST
              value: "{{ .Values.redis.host }}"
            - name: REDIS_ENABLED
              value: "{{ .Values.redis.enabled }}"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.httpPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.httpPort }}
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
